<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CONTROLLER\__Controller.cs" />
    <Compile Remove="CONTROLLER\__Game.cs" />
    <Compile Remove="VIEW\__Renderer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pastel" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
